import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { DATA } from "@/data/resume";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  metadataBase: new URL(DATA.url),
  title: {
    default: DATA.name,
    template: `%s | ${DATA.name}`,
  },
  description: DATA.description,
  keywords: [
    "ahtesham",
    "Ahtesham",
    "Ahtesham Zaman",
    "ahtesham zaman",
    "ahtesham.tech", 
    "Zaman.tech", 
    "Software Engineer", 
    "Developer", 
    "software developer",
    "best website development agency",
    "best website development agency in jajpur town",
    "best website development agency in bhubaneshwar",
    "best website development agency in bhubaneswar",
    "best website development agency in odisha",
    "web development agency",
    "mobile app development development agency",
    "mobile app design development agency",
    "web design development agency",
    "website design development agency",
    "devxplore",
    "best development agency",
    "devxplore.tech",
    "devxplore reviews",
    "technology solutions",
    "website development",
    "mobile app development",
    "custom software development",
    "tech startup",
    "enterprise software solutions",
    "web design",
    "mobile UX design",
    "local tech company",
    "software development",
    "devxplore portfolio",
    "IT consultancy",
    "digital transformation",
    "cloud services",
    "AI solutions",
    "blockchain development",
    "SaaS development",
    "e-commerce solutions",
    "agile development",
    "tech innovation",
    "digital agency",
    "tech consultancy",
    "MVP development",
    "full-stack development",
    "web application development",
    "cross-platform app development",
    "responsive web design",
    "user interface design",
    "user experience optimization",
    "backend development services",
    "frontend development services",
    "tech stack modernization",
    "API development services",
    "system integration services",
    "React development services",
    "AngularJS development company",
    "Node.js backend development",
    "mobile development with Flutter",
    "iOS and Android app development",
    "progressive web app solutions",
    "custom CRM solutions",
    "ERP software development",
    "cloud infrastructure services",
    "DevOps consulting services",
    "fintech software development",
    "edtech web solutions",
    "healthcare app development",
    "real estate website development",
    "e-commerce web developers",
    "travel app development",
    "retail mobile app solutions",
    "sports app developers",
    "entertainment software solutions",
    "automotive app development",
    "software development services NYC",
    "London tech consultancies",
    "Silicon Valley app developers",
    "UK-based UX designers",
    "US tech solution experts",
    "mobile development firms in USA",
    "web vikas company India",
    "mobile app banane wali company",
    "Bharat mein software solutions",
    "startup tech support India",
    "online business solutions provider India",
    "how to build an ecommerce website",
    "best mobile app developers for startups",
    "affordable UX design services in USA",
    "enterprise software development in London",
    "custom web development for small businesses",
    "full-stack developers for hire in India",
    "outsourcing web projects to India",
    "outsourcing web development projects to India",
    "best website development agency in india",
    "Best web development company",
    "Custom website development services",
    "Top web development agency",
    "Affordable web development solutions",
    "Web development for small businesses",
    "Professional website developers",
    "Enterprise web development services",
    "Custom software development company",
    "Full-stack web development services",
    "Responsive web design company",
    "Mobile app development company",
    "iOS app development services",
    "Android app development company",
    "Cross-platform app developers",
    "Custom mobile app development",
    "Affordable mobile app solutions",
    "Top mobile app developers",
    "Best mobile app design agency",
    "Mobile UX/UI design services",
    "Progressive web app development",
    "E-commerce website development",
    "Custom e-commerce solutions",
    "Shopify development experts",
    "Magento development company",
    "WooCommerce developers for hire",
    "Affordable e-commerce website builders",
    "Best e-commerce website design",
    "Enterprise e-commerce platforms",
    "E-commerce SEO services",
    "E-commerce app development",
    "Best web development company in India",
    "Affordable web developers in Bangalore",
    "Top web design agency in Delhi",
    "Custom website development Mumbai",
    "Mobile app development in Hyderabad",
    "Web development services in Pune",
    "E-commerce website developers in Chennai",
    "Full-stack developers in Kolkata",
    "Best software development in Ahmedabad",
    "Digital marketing agency in Jaipur",
    "Web development company in Dubai",
    "Mobile app developers in Dubai",
    "Custom website design Dubai",
    "E-commerce solutions in UAE",
    "Best digital agency in Dubai",
    "Affordable web designers in Dubai",
    "Top app development companies in UAE",
    "Full-stack developers in Dubai",
    "Dubai software development services",
    "Digital transformation in Dubai",
    "Web development company in Saudi Arabia",
    "Mobile app developers in Riyadh",
    "Custom software development Jeddah",
    "E-commerce solutions Saudi Arabia",
    "Best digital agency in Riyadh",
    "Affordable web designers in Saudi Arabia",
    "Top app development companies in Saudi",
    "Full-stack developers in Jeddah",
    "Saudi Arabia software development services",
    "Digital transformation in Saudi Arabia",
    "Best web development company in USA",
    "Top mobile app developers in NYC",
    "Affordable web designers in Los Angeles",
    "Custom website development San Francisco",
    "Mobile app development services in Chicago",
    "E-commerce development in Miami",
    "Full-stack developers in Texas",
    "USA-based software development services",
    "Web design agency in New York",
    "Digital marketing agency in California",
    "Healthcare web development services",
    "Real estate website developers",
    "Education website development",
    "Fintech app development company",
    "Retail e-commerce website design",
    "Travel website development agency",
    "Hospitality web development services",
    "Automotive website design",
    "Sports app development company",
    "Entertainment industry web developers",
    "React.js development services",
    "AngularJS development company",
    "Node.js backend developers",
    "Vue.js web development",
    "Python development services",
    "Ruby on Rails web developers",
    "PHP web development company",
    "Laravel development services",
    "API integration services",
    "DevOps consulting for web development",
    "Blockchain development company",
    "SaaS application development",
    "Custom CRM development services",
    "ERP software solutions provider",
    "AI-driven web development company",
    "Cloud-based web solutions",
    "IoT app development services",
    "Digital transformation consulting",
    "Custom CMS development",
    "WordPress development experts",
    "Drupal development company",
    "Joomla website development",
    "Magento e-commerce solutions",
    "Shopify plus development experts",
    "BigCommerce website development",
    "WooCommerce developers for hire",
    "Custom payment gateway integration",
    "Social media integration for websites",
    "SEO-friendly web development",
    "PPC management for e-commerce websites",
    "Content management system development",
    "Website maintenance and support",
    "Web hosting services for businesses",
    "Cloud migration services",
    "Custom web application development",
    "Mobile-first web design agency",
    "High-performance website optimization",
    "Website security solutions provider",
    "GDPR-compliant web development",
    "ADA-compliant website design",
    "Online booking system development",
    "Custom inventory management solutions",
    "Real-time data analytics for websites",
    "Enterprise-level website development",
    "Interactive web design services",
    "AI chatbots for websites",
    "Voice search optimization for websites",
    "Custom API development services",
    "Multi-language website development",
    "Website accessibility solutions",
    "Video streaming website development",
    "Real-time web applications",
    "Progressive web app (PWA) development",
    "Hybrid mobile app development",
    "Augmented reality (AR) web development",
    "Virtual reality (VR) app development",
    "AI-powered web solutions",
    "Machine learning integration for websites",
    "Blockchain-based website development",
    "Cryptocurrency website development",
    "website development agency",
    "web development agency",
    "mobile app development development agency",
    "mobile app design development agency",
    "web design development agency",
    "website design development agency",
    "devxplore",
    "best development agency",
    "devxplore.tech",
    "devxplore reviews",
    "technology solutions",
    "website development",
    "mobile app development",
    "custom software development",
    "tech startup",
    "enterprise software solutions",
    "web design",
    "mobile UX design",
    "local tech company",
    "software development",
    "devxplore portfolio",
    "IT consultancy",
    "digital transformation",
    "cloud services",
    "AI solutions",
    "blockchain development",
    "SaaS development",
    "e-commerce solutions",
    "agile development",
    "tech innovation",
    "digital agency",
    "tech consultancy",
    "MVP development",
    "full-stack development",
    "web application development",
    "cross-platform app development",
    "responsive web design",
    "user interface design",
    "user experience optimization",
    "backend development services",
    "frontend development services",
    "tech stack modernization",
    "API development services",
    "system integration services",
    "React development services",
    "AngularJS development company",
    "Node.js backend development",
    "mobile development with Flutter",
    "iOS and Android app development",
    "progressive web app solutions",
    "custom CRM solutions",
    "ERP software development",
    "cloud infrastructure services",
    "DevOps consulting services",
    "fintech software development",
    "edtech web solutions",
    "healthcare app development",
    "real estate website development",
    "e-commerce web developers",
    "travel app development",
    "retail mobile app solutions",
    "sports app developers",
    "entertainment software solutions",
    "automotive app development",
    "software development services NYC",
    "London tech consultancies",
    "Silicon Valley app developers",
    "UK-based UX designers",
    "US tech solution experts",
    "mobile development firms in USA",
    "web vikas company India",
    "mobile app banane wali company",
    "Bharat mein software solutions",
    "startup tech support India",
    "online business solutions provider India",
    "how to build an ecommerce website",
    "best mobile app developers for startups",
    "affordable UX design services in USA",
    "enterprise software development in London",
    "custom web development for small businesses",
    "full-stack developers for hire in India",
    "outsourcing web projects to India",
    "outsourcing web development projects to India",
    "best website developemnt agency in india",
    // Core Keywords
    "website development agency",
    "web development agency",
    "mobile app development agency",
    "web design development agency",
    "best development agency",
    "technology solutions",
    "custom software development",
    "enterprise software solutions",
    "full-stack development",
    // Location-Based Keywords
    "web development company in India",
    "mobile app developers in Bangalore",
    "web design services in Delhi",
    "custom website development Mumbai",
    "e-commerce development in Dubai",
    "software solutions in Saudi Arabia",
    "web development company in USA",
    "tech solutions in UK",
    "mobile app developers in UAE",
    // Service-Specific Keywords
    "e-commerce website development",
    "mobile app development services",
    "custom CRM solutions",
    "ERP software development",
    "cloud infrastructure services",
    "AI-driven web development",
    "blockchain development services",
    "SaaS development company",
    "agile development practices",
    // Industry-Specific Keywords
    "fintech software development",
    "healthcare app development",
    "real estate website development",
    "edtech web solutions",
    "retail mobile app solutions",
    "sports app developers",
    "entertainment software solutions",
    "automotive app development",
    "travel app development services",
    // Tech-Specific Keywords
    "React.js development services",
    "AngularJS development company",
    "Node.js backend development",
    "Python development services",
    "PHP web development",
    "Laravel development experts",
    "API integration services",
    "DevOps consulting services",
    "machine learning integration",
    // Marketing Keywords
    "SEO services for e-commerce",
    "PPC management for websites",
    "digital marketing solutions",
    "content marketing for tech companies",
    "social media integration for websites",
    "local SEO services",
    "online reputation management",
    "conversion rate optimization",
    "email marketing strategies",
    // Extended Long-Tail Keywords
    "affordable web design services in India",
    "custom mobile app development for startups",
    "best digital marketing agency in Dubai",
    "top web development companies in Saudi Arabia",
    "e-commerce SEO services in USA",
    "responsive web design for small businesses",
    "cloud-based software solutions in UK",
    "AI chatbots for customer service",
    "mobile-first website design",
    // Regional Focus Keywords
    "web development agency in Mumbai",
    "best mobile app developers in Delhi",
    "e-commerce website builders in Chennai",
    "cloud services in Hyderabad",
    "custom software solutions in Kolkata",
    "web design agency in Pune",
    "IT consultancy in Bangalore",
    "software development in Ahmedabad",
    "top tech startups in Jaipur",
    // Expanded Service Offerings
    "cross-platform app development",
    "progressive web app solutions",
    "custom API development",
    "system integration services",
    "multi-language website development",
    "voice search optimization",
    "ADA-compliant website design",
    "GDPR-compliant web development",
    "AI-powered mobile apps",
    // Location-Specific Expansion
    "web development company in Dubai",
    "mobile app developers in Saudi Arabia",
    "e-commerce solutions in UAE",
    "tech consultancy in London",
    "app developers in New York",
    "website designers in San Francisco",
    "custom software developers in Los Angeles",
    "mobile app design in Chicago",
    "web application development in Miami",
    // Niche Focus Keywords
    "fintech app developers in India",
    "healthcare IT solutions in USA",
    "real estate tech solutions in Dubai",
    "travel technology solutions",
    "retail e-commerce solutions",
    "automotive software development",
    "sports technology development",
    "entertainment industry software",
    "education technology development",
    // Content-Driven Keywords
    "how to build an ecommerce website",
    "best mobile app developers for startups",
    "affordable UX design services in USA",
    "enterprise software development in London",
    "custom web development for small businesses",
    "full-stack developers for hire in India",
    "outsourcing web projects to India",
    "AI in mobile app development",
    "blockchain for e-commerce",
    // Targeting Global Markets
    "top web development agency in Dubai",
    "leading mobile app developers in Saudi Arabia",
    "enterprise software solutions in USA",
    "custom website builders in UK",
    "e-commerce solutions in Europe",
    "web development for startups in Silicon Valley",
    "mobile app development for fintech",
    "AI-powered websites in Germany",
    "tech innovation in Canada",
    // Additional Long-Tail Keywords
    "best digital marketing agency in UAE",
    "affordable software development in India",
    "custom CRM development for retail",
    "cloud migration services in USA",
    "mobile UX design for e-commerce",
    "responsive web design for real estate",
    "API development services in Europe",
    "machine learning for mobile apps",
    "augmented reality in mobile development",
    // Location-Based Expansion
    "top software development companies in Dubai",
    "mobile app development in Riyadh",
    "custom software solutions in Jeddah",
    "e-commerce development in Abu Dhabi",
    "tech startups in Dubai",
    "web design services in Qatar",
    "software development in Kuwait",
    "mobile app development in Oman",
    "cloud services in Bahrain",
    // Service and Solution Keywords
    "custom software solutions for fintech",
    "mobile app development for healthcare",
    "AI-driven e-commerce solutions",
    "blockchain for supply chain management",
    "cloud-based ERP solutions",
    "enterprise software for real estate",
    "web development for government projects",
    "mobile app development for education",
    "tech consultancy for startups",
    // Specific Market Focus
    "e-commerce solutions in Saudi Arabia",
    "web development for healthcare in India",
    "mobile app developers for fintech in Dubai",
    "custom software for logistics",
    "cloud-based solutions for education",
    "AI in healthcare technology",
    "blockchain for financial services",
    "web design for non-profits",
    "mobile app development for sports",
    // Specialized Keywords
    "e-commerce app development in USA",
    "custom CRM for e-commerce",
    "ERP solutions for small businesses",
    "mobile UX design for education",
    "responsive web design for startups",
    "API integration for mobile apps",
    "AI chatbots for healthcare",
    "voice search optimization for e-commerce",
    "custom inventory management systems",
    // Further Long-Tail Keywords
    "best cloud migration services in UAE",
    "top mobile app developers in Saudi Arabia",
    "custom blockchain solutions for finance",
    "AI-driven web applications",
    "custom software development for startups",
    "best digital agency for healthcare",
    "mobile app development for logistics",
    "cloud-based tech solutions in India",
    "web design services for education",
    // Technology and Innovation Keywords
    "AI-powered fintech solutions",
    "custom SaaS development",
    "augmented reality for mobile apps",
    "virtual reality app development",
    "cloud infrastructure for enterprises",
    "machine learning for e-commerce",
    "blockchain for real estate",
    "custom ERP systems for enterprises",
    "AI in retail technology",
    // Additional Service Offerings
    "web hosting services in USA",
    "cloud-based software in UK",
    "custom API development in India",
    "web development for financial services",
    "e-commerce SEO in Dubai",
    "mobile app security solutions",
    "API integration for fintech",
    "tech solutions for small businesses",
    "website maintenance and support",
    // Targeting Niche Markets
    "custom web design for legal firms",
    "mobile app development for non-profits",
    "web development for entertainment industry",
    "cloud-based solutions for real estate",
    "AI-driven marketing automation",
    "blockchain for healthcare records",
    "web design for online courses",
    "mobile app development for travel",
    "custom software for retail management",
    // Expanding Global Reach
    "e-commerce solutions in Australia",
    "mobile app development in Singapore",
    "web design services in Malaysia",
    "custom software in Hong Kong",
    "tech solutions in South Africa",
    "web development for startups in Japan",
    "AI-driven tech solutions in Brazil",
    "blockchain development in Mexico",
    "mobile app developers in Argentina",
    "web design services in South Korea",
  ].join(", "),
  openGraph: {
    title: `${DATA.name}`,
    description: DATA.description,
    url: DATA.url,
    siteName: `${DATA.name}`,
    locale: "en_US",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  twitter: {
    title: `${DATA.name}`,
    card: "summary_large_image",
  },
  verification: {
    google: "",
    yandex: "",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased max-w-4xl mx-auto py-12 sm:py-24 px-6",
          fontSans.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <TooltipProvider delayDuration={0}>
            {children}
            <Navbar />
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
